### ISSUE TITLE
Horaro export: setup time is not reflected

### ISSUE THREAD

**Issue by Hoishin** [oengusio/oengusio#131]
### Describe the bug

When you export JSON for Horaro, setup time column is wrong
![image](https://user-images.githubusercontent.com/28832095/141651422-c3944b8e-222c-4dc2-84d2-00bcd4c1807d.png)

### How to reproduce

1. set a run with different setup time
2. export horaro schedule
3. import to a horaro event

### Expected behavior

it should set setup time column correctly

### Desktop (please complete the following information)

- OS: Windows
- Browser: Chrome
- Version: Windows 10, Chrome 95

**Comment by duncte123** [comment]
Is this still an issue?

**Comment by duncte123** [comment]
Closing due to no response
