### ISSUE TITLE
I'm being improperly filtered out

### ISSUE THREAD

**Issue by Rabbiratelier** [oengusio/oengusio#176]
### Describe the bug

For each submission I made, it doesn't show up on the "View submissions" page when I apply a filter that should match the status of the submission.
My name: MafuyuKinoshita
https://oengus.io/en-GB/marathon/pgrf4/submissions (Accepted)
https://oengus.io/en-GB/marathon/IRM2023/submissions (Declined)

### How to reproduce

1. Go to the "View submissions" page of an event submitted by someone affected by this bug.
2. Filter it to display the submission they made.
3. Always works. It doesn't show the submission.

### Expected behavior

All of the submissions that match the filter will be displayed, including mine.

### Desktop (please complete the following information)

- OS: [win11]
- Browser [ms edge]
- Version [121.0.2220.3 (official build) dev (64 bit), 119.0.2151.72 (official build) (64 bit)]

**Comment by duncte123** [comment]
Can seem to find them when status is set to "All", thanks for reporting

**Comment by duncte123** [comment]
Hey, would you mind trying again to see if the search works better now?

**Comment by Rabbiratelier** [comment]
I have tried the same thing several times and it still does not work...
As you said earlier, yes, it seems that the problem is that pagination stops working when the status is set to anything other than "All".

**Comment by duncte123** [comment]
Has been fixed, will be published with the next release

**Comment by duncte123** [comment]
Oengus has been updated, I can confirm that this is fixed now
