### ISSUE TITLE
Mastodon Regex is inconsistent between frontend and backend

### ISSUE THREAD

**Issue by lepelog** [oengusio/oengusio#217]
### Describe the bug

[Client Regex](https://github.com/oengusio/oengus-webapp/blob/eb54ea2ca172e7fce8081a10ceab24d71f70f638/src/utils/helpers.ts#L3) allows leading '@'
[Server Regex](https://github.com/oengusio/oengusio/blob/5a2f1666cbc97c79a9c1605e86782f63df0d8d23/src/main/java/app/oengus/adapter/rest/dto/v1/UserDto.java#L28) does not allow it.

Usually fediverse accounts use `@abc@server` to distinguish themselves from emails. But to keep the fix simple, I would do something like strip the leading '@' when saving.

I can probably contribute a fix.

### How to reproduce

1. Go to https://oengus.io/user/settings
2. Click on the plus button to add a new social media connection
3. Select Mastodon
4. Enter `@test@test.de` as the username
5. Save
6. Error message (from the api): `{"path":"/v1/users/247","method":"PATCH","type":"ConstraintViolationException","message":"Validation failed for classes [app.oengus.adapter.jpa.entity.SocialAccount] during persist time for groups [javax.validation.groups.Default, ]\nList of constraint violations:[\n\tConstraintViolationImpl{interpolatedMessage='The username does not have a valid format for the platform', propertyPath=usernameValidForPlatform, rootBeanClass=class app.oengus.adapter.jpa.entity.SocialAccount, messageTemplate='The username does not have a valid format for the platform'}\n]","errors":[{"rootBeanClass":"class app.oengus.adapter.jpa.entity.SocialAccount","message":"The username does not have a valid format for the platform","propertyPath":"usernameValidForPlatform"}]}`

### Expected behavior

Saving should work without error

### Desktop (please complete the following information)

- OS: Linux 6.12.1-4-MANJARO
- Browser firefox
- Version 133.0

**Comment by duncte123** [comment]
Lol derp, leading `@` should be allowed and the front-end should parse the domain and build the url appropriately when rendering the user's profile.

Great test case for backend unit testing as well :)
